#!/bin/bash

# This file is part of INSECA.
#
#    Copyright (C) 2022 INSECA authors
#
#    INSECA is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    INSECA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with INSECA.  If not, see <https://www.gnu.org/licenses/>

type_conf="/etc/inseca-display-type"
dtype=$(cat "$type_conf")
cp /etc/gdm3/daemon.conf /etc/gdm3/daemon.conf.VMA
logger "Display type: [$dtype]"
if [ "$dtype" == "x11" ]
then
    sed -i -e "s/^#\{0,1\}WaylandEnable=.*/WaylandEnable=false/" /etc/gdm3/daemon.conf
    logger "Set display to X11"
else
    sed -i -e "s/^#\{0,1\}WaylandEnable=.*/WaylandEnable=true/" /etc/gdm3/daemon.conf
    logger "Set display to wayland"
fi
