#!/bin/sh

# This file is part of INSECA.
#
#    Copyright (C) 2020-2022 INSECA authors
#
#    INSECA is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    INSECA is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with INSECA.  If not, see <https://www.gnu.org/licenses/>

# remove the sudoers's file which grants the live user full root access
rm -f /etc/sudoers.d/live
gpasswd -d insecauser sudo

# remove the polkit policy which grants the live user all the privileges
rm -f /var/lib/polkit-1/localauthority/10-vendor.d/10-live-cd.pkla
